travis:
  secure:
    BINSTAR_TOKEN: CwQ+ODC02CSJKv9S1fUWxCFGFwzHGHk+t80jrvq9nE0mc2dhNAE+H0qI6sb6pTe9atQ/7LBfZgYd9Cu3yPSdJDyqwB2NN5wXdBW5niKOznOlP2KLxJrSLLbdvwHCfPXz79BWntoRFtrCfu6dehyneAmQ+6H4nxL15ntJT2YhsrJhPYCGTprPb+hSrUzOeK1JRoMbbME9cUwUGs/kfwHDNg+R1u1eDQTW8KCNfwbLLvoz5TVjOvfTgdPD+jUmj+lz4JiLPsa2XUr1iV4LJCwRztkfooBc04IMypSE2MC54tjsVz5MMGIr0xfUPGXfF/AfKF5g49GItJERky2k4MHTzR5r8yFgFC6kk+6g06WP5II91oUItjCKRF4dZux+BjKJx/JfkOVhH8VuS5ZR46TfBlq6tgIvTaXA8XlXSs20KkOrkTw4ZqpTvYSyKNs9M58IosHRrlirM95LYvGG925hDvMWYs8gUthSpu7x95mrv4YIJJRDdxbGMm1jts9SSSCzqRYr3CEenIFreT5okIO1uddCdEJl+5wlUcizjmebTTBjI424coMgRZSJafJ1v+8feTiWMYhqB6Ib64Dwp0WzUrk2ATN+AU9tn1wiACSfFsepSjH9GiWvESFqqnHzwocxFaRI8JIOp2hGju8utDl7PXSUvSmDaOvTJ9VdqR3OBSo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
