travis:
  secure:
    BINSTAR_TOKEN: QKbyKS9u8xsk3bVWeEgp5GNr3c/BmGvniwrHD6HQZWz0xLVbUSxCqraGUvTZS7Klf8BoheGXomdNVdGH8fGXknA9e86LZzGIXz5+k8qdyZlnGmdnY8cG6FAH68h/SThr7oyswZl1Mi6Cu5kdT7452qgu4Y5sKesybJYxDcjNEHe7hosuH/aWfs4QYh5ak9mfEw7YGIGjuqFtm1gWsnW47wYnxKQVf6SVVjizJQM3n9a5kNGW0Rtabc/cqRiTd1vHzN+SSlbMRn6w+g5MOgzmTuhJi3IjhitYDYjfRocoae3l4RD9CxBv6AiziO6PsyOvM+ytHSszsxREfU+QvnjSIl1cBSUejmHUgjvqMtSXMRZt34qOCZzSXqTkZsjC9IjSsaFRSwjmNY0P02r8ZknhsKevSi6k2GShyD6+x/KrGxBskx5Ox40fpBBHWenAX6ErdqrbwBBbIBP37pDxh9itGBmsjltcReCQkzqzvHtZijs1aRXImqElBvIejWBMlcfdPCbmt090gVRxA3SDOLVQb4iqBk2eVfYLscZrPDXVsM2DgojXD+3d44czVGmGFRFfIKhjQDQWR3qs57WNYkFYaCEQr8puNyEzh1UVKcZ31Q/BaTerqBsbO1LcJAOE/Cu+4Wdq8S+i+HRi7Z/+AacRV2R8fZIkWJRzV5T8uORKMdk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
