travis:
  secure:
    BINSTAR_TOKEN: WW9/SwBiYNq/DJGd6bQUFjPBy+yxgiaqvq2DhMGwS8a5LzPDmOA0MRBMfD9jaIXiEtAbeKnmtxFRzsg36ABSGR7E9AAX2uG4XDuCAYHKihj/UCGlMMGBZtiOmolxhZNO8+4Euvj3qLvq/f5pQH9ldMAfdlG8GxOLrECA/uy9XqJ7aiOVTuzhT0bHuYWxuLyNkqHttYkXSQi5B2BFQGaeuq56K3QU8nKdqzRRfV5DdX+MI4NNZ46zPoOYbkW0sp+yseG5saAcx14ub7CI6zgc8j6MkrD6pn9sePPpWeiSrRkeLhopCltf9XM8TNWnkiNjV5QHTK3lsdhbDJrtm4YaFBoUGfWV2i+I4iu5rIdAq/OqSQv5qR/Brjbydd0mSzUw4Mjetbun1rrPWCy0Mwdiv83wQ3JTwjIGy2TOogD/meBXVKKstkuRg7P4uGTgCxHL9KDEoGJI9VYxaJDCLoPyOx2JdouP3WQ+Pz+Jtb442pgFftUyeUrSdTABexh0LqEu8VVUcOIfRChZuoK7IXmUwfcLvNP6VStEg+iLGgsZzCbKijej49foYW/c9gxw1Z+nAQSLaN34hAtwoX9lwHkMB/HkwLH9amfpEsBaiopvXhOoeppJfHjZyqiq7CjVhNxciscNSMOSigdb8KZ4y506Esv4JObPvwcAOWdoXtz+aNI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
