appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: HscZoe4WTx5cyqimoYlmF6oqpi376vsvCPktqXVmnKr8Qv0pdG7/nl1qvseQsndiyJBLUHMhA9XiPxytGkUmiFCWzxv/GQ4xt+8yc+y7DByR5Yx9L7Cwm1x9cSfn1t1lbZ5RbnY/XkeIAV7FGM0lcspft2Jr+D4rUYqSbLmC8GNkLTYXN0Gt4bhqukMCXuwwPMlPAygtSnqCDyus17vLkfSB4SZDi+HEUBCI7Mnl2w2asmz1MtnJ9f58bDLMQ7h7PmS+T3L8ALqo49lvdvjyI8/Q5C6+/wcs31yxCAmtcnWeNs2CInc77OytLLtBGIOmwv3vp/U7QRj4JQapL8+Xwtnbm0KsmCe0Wrt83xEmCgv8bS7gx5DrRS23+yLlvJUCveHeMFlEkJ9YBAGHXAKWj/00e8RTAoKR+DG29Da2ehSQayIou5TnhkbiafWU1GVvn222JlDXCafc709Y0K3R+JuvmoyApB6dsNNaHaHtgVxHaqJxkJzn+lDXZ8HcuwIf2ZilKcbSzS0C3hGhQWTULyLzwBeGRuq1Oe8pHC6zkIxSDRrZglXbnpHBiQ6uk23sQJyx/nr2Tm1htiZIU3ix78xQma58ZX4fvE6Khie7+Q+46RAGuW+1vlPlKzBt+WNIJ/6hzgLGS4e2evwoio0rI63rVr8CwpJhI4V+7uPt74k=}
